sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - ruby-head
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
script:
  - bundle exec rspec
matrix:
  allow_failures:
    - rvm: ruby-head
gemfile:
  - gemfiles/clockwork_master.gemfile
  - gemfiles/clockwork_2_0_4.gemfile
