sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - ruby-head
script:
  - bundle exec rspec
matrix:
  allow_failures:
    - rvm: ruby-head
gemfile:
  - gemfiles/clockwork_master.gemfile
  - gemfiles/clockwork_1_3_1.gemfile
  - gemfiles/clockwork_2_0_0.gemfile
  - gemfiles/clockwork_2_0_1.gemfile
  - gemfiles/clockwork_2_0_2.gemfile
  - gemfiles/clockwork_2_0_3.gemfile
